### PR TITLE
Adds an error page

### LINKED ISSUE #1: Implement an error page
Show an error page to the user for when an error occurs from/in the API

# Acceptance criteria

- [ ] Add an error page

### PR DESCRIPTION
**Pull request by Karyum**
close #1

what do you think of my message?

### CODE REVIEW

**Comment by Karyum** [comment]
@shiryz can we actually be done with this ?

**Comment by shiryz** [comment]
@Karyum close?

**Comment by Karyum** [comment]
@shiryz no i actually need this, just need to make the change in the message :sweat_smile:

**Comment by Karyum** [comment]
@shiryz don't judge me :laughing:

**Pull request merged**
